server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://123.249.83.65:3306/mydb?useSSL=false
    username: root
    password: 159735
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id